name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: carina_github_project
          cx_tenant: sqa_perf_single_tenant
          base_uri: https://st-rc.perf.cxast.net/
          cx_client_id: carina_githug
          cx_client_secret: 4vKL7ZvGfHiaLgDPd8uzKgUUSKzPbiYB
